#!/usr/bin/env ansible-playbook
---
- name: play01
  remote_user: root
  hosts: self
  tasks:
  - name: set hasProfile
    ansible.builtin.set_fact:
      hasProfile: yeahyes
  - name: debug hasProfile
    ansible.builtin.debug:
      var: hasProfile
