#!/usr/bin/env ansible-playbook
---
- vars:
    one: 1
    two: 2
  ansible.builtin.import_playbook: foo.yml
- name: play00
  remote_user: root
  hosts: self
  tasks:
  - ansible.builtin.meta: end_play
  - name: install programs
    ansible.builtin.apt:
      name:
      - firefox
      - vim
  - name: install thunderbird
    community.general.pacman:
      name:
      - thunderbird
      - obs
